from fpdf import FPDF
import os
from datetime import datetime

class PDFService:
    def __init__(self):
        self.font_path = os.path.join(os.getcwd(), "backend", "data", "fonts")

    def create_report(self, data: dict) -> bytes:
        """
        Generates a PDF report based on the provided data.
        data structure expected:
        {
            "candidate_name": str,
            "role": str,
            "session_id": str,
            "executive_summary": str,
            "top_skills": [{"name": str, "level": int/str, "evidence": str}],
            "communication_style": str,
            "verdict": str,
            "score_breakdown": {"name": int, ...} # Optional
        }
        """
        pdf = FPDF()
        pdf.add_page()
        
        # Colors
        COLOR_BG = (10, 10, 20)
        COLOR_ACCENT = (0, 150, 255)
        COLOR_TEXT_MAIN = (40, 40, 50)
        COLOR_TEXT_SUB = (100, 100, 110)

        # 1. Header
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*COLOR_TEXT_SUB)
        pdf.cell(0, 50, f"ID: {data.get('session_id', 'UNKNOWN')}", align="R", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_y(15)
        pdf.set_font("Helvetica", "B", 24)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "SOURCE PERSONA", new_x="LMARGIN", new_y="NEXT", align="L")
        
        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(*COLOR_ACCENT)
        pdf.cell(0, 10, "TECHNICAL DUE DILIGENCE REPORT", new_x="LMARGIN", new_y="NEXT", align="L")
        
        pdf.ln(10)
        
        # 2. Candidate Profile
        pdf.set_fill_color(240, 240, 250)
        pdf.rect(10, pdf.get_y(), 190, 25, 'F')
        
        current_y = pdf.get_y() + 5
        pdf.set_xy(15, current_y)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(100, 10, data.get("candidate_name", "Unknown Candidate"))
        
        pdf.set_xy(15, current_y + 8)
        pdf.set_font("Helvetica", "I", 12)
        pdf.set_text_color(*COLOR_TEXT_SUB)
        pdf.cell(100, 10, data.get("role", "Software Engineer"))
        
        pdf.set_xy(120, current_y + 2)
        pdf.set_font("Helvetica", "B", 14)
        # Verdict Color logic
        verdict = data.get("verdict", "REVIEW").upper()
        if "HIRE" in verdict:
            pdf.set_text_color(0, 180, 100) # Green
        else:
            pdf.set_text_color(200, 50, 50) # Red
            
        pdf.cell(80, 10, verdict, align="R")
        
        pdf.set_xy(10, current_y + 25) # Move below box
        pdf.ln(10)

        # 3. Executive Summary
        self._section_title(pdf, "EXECUTIVE SUMMARY")
        pdf.set_font("Times", "", 12)
        pdf.set_text_color(*COLOR_TEXT_MAIN)
        pdf.multi_cell(0, 6, data.get("executive_summary", "No summary provided."))
        pdf.ln(5)

        # 4. Top Skills (Visual)
        self._section_title(pdf, "KEY COMPETENCIES")
        
        skills = data.get("top_skills", [])
        for skill in skills:
            skill_name = skill.get("name", "Skill")
            evidence = skill.get("evidence", "")
            
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 8, skill_name, new_x="LMARGIN", new_y="NEXT")
            
            pdf.set_font("Times", "", 10)
            pdf.multi_cell(0, 5, f"Proof: {evidence}")
            pdf.ln(2)

        pdf.ln(5)

        # 5. Communication Analysis
        self._section_title(pdf, "COMMUNICATION PROTOCOL AUDIT")
        pdf.set_font("Times", "", 11)
        pdf.multi_cell(0, 6, data.get("communication_style", "N/A"))
        pdf.ln(10)

        # 6. Disclaimer / Footer
        pdf.set_y(-30)
        pdf.set_font("Courier", "", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.multi_cell(0, 4, "Generated by Veronika's Digital Twin Neural Interface.\nThis document is a generated artifact and does not constitute a legally binding contract.\nSession Timestamp: " + datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

        return bytes(pdf.output())

    def _section_title(self, pdf, title):
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        pdf.line(pdf.get_x(), pdf.get_y(), 200, pdf.get_y()) # Underline
        pdf.ln(2)
